version: "3"
services:
  php-fpm:
    build:
      context: ./conf/php-fpm
      args:
        - TZ=${TZ}
    image: php-ext
    ports:
      - ${HOST_PHP_PORT}:${PHP_PORT}
    volumes:
      - ./conf/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./logs:/var/log/php
      - ${APP_SOURCE_PATH}:/app_src
    working_dir: /app_src
    environment:
      # TimeZone
      - TZ=${TZ}
      # Laravel Environments
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  postgres:
    restart: always
    image: postgres:12.2-alpine
    ports:
      - ${HOST_DB_PORT}:${DB_PORT}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./conf/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./conf/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./conf/postgres/pg_ident.conf:/etc/postgresql/pg_ident.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      # TimeZone
      TZ: ${TZ}
      # PostgreSQL Environments
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=ja_JP.UTF-8'
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  nginx:
    image: nginx:1.16.1-alpine
    depends_on:
      - postgres
      - php-fpm
    ports:
      - ${HOST_HTTP_PORT}:${HTTP_PORT}
    volumes:
      - ${APP_SOURCE_PATH}:/app_src
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    environment:
      - TZ=${TZ}
